### ISSUE TITLE
Ps1 optimization seems redundant

### ISSUE THREAD

**Issue by oganm** [daattali/rasperry-pi-gaming-console-setup#1]
All settings you described in PS1 optimization is already set by overclocking to turbo. The only missing option was `force_turbo=0` but what does that do anyway?

**Comment by daattali** [comment]
I don't think it automatically did that for me.  I'll leave this issue open until I check again.   All the settings are described [here](http://elinux.org/RPiconfig)

**Comment by daattali** [comment]
I never ended up checking again. What made you find this open issue?

**Comment by oganm** [comment]
Made my own setup and noticed a bit wasn't necessary. Closed it now to clear up my Issues list a little
